import re
links = ''''
https://webcache.googleusercontent.com/search?q=cache:s6OApqg5qWEJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/seishun_prologue.pdf+&cd=2&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:s6OApqg5qWEJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/seishun_prologue.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/here_junna_mahoutsukai_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/renai_circulation_bakemonogatari_op4.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/update_bnha_s3_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:Ie_FjTiWi4cJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/uchiage_hanabi.pdf+&cd=10&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:Ie_FjTiWi4cJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/uchiage_hanabi.pdf+
https://webcache.googleusercontent.com/search?q=cache:N9xI6jYv5OQJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/double_rainbow_dreams.pdf+&cd=7&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:N9xI6jYv5OQJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/double_rainbow_dreams.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/make_my_story_bhna_s3_op2.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/seishun_prologue.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/uchiage_hanabi.pdf
https://webcache.googleusercontent.com/search?q=cache:6Ub34F_HtlwJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/renai_circulation_bakemonogatari_op4.pdf+&cd=4&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:6Ub34F_HtlwJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/renai_circulation_bakemonogatari_op4.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/switch_highschool_dxd_hero_op.pdf
https://webcache.googleusercontent.com/search?q=cache:vvLm7YBzUV0J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/make_my_story_bhna_s3_op2.pdf+&cd=8&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:vvLm7YBzUV0J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/make_my_story_bhna_s3_op2.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/voracity_overlord_iii_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/double_rainbow_dreams.pdf
https://webcache.googleusercontent.com/search?q=cache:6lIjlRN2vZQJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/update_bnha_s3_ed.pdf+&cd=9&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:6lIjlRN2vZQJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/update_bnha_s3_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:jyGjATEfLSQJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/voracity_overlord_iii_op.pdf+&cd=6&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:jyGjATEfLSQJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/voracity_overlord_iii_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:bfauhK0ds14J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/here_junna_mahoutsukai_op.pdf+&cd=3&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:bfauhK0ds14J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/here_junna_mahoutsukai_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:1-ayoNtn7WMJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/switch_highschool_dxd_hero_op.pdf+&cd=5&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:1-ayoNtn7WMJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/switch_highschool_dxd_hero_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/iwanai_kedo_ne_karakai_jouzu.pdf
https://webcache.googleusercontent.com/search?q=cache:FSS0qP5aV-cJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/senbonzakura.pdf+&cd=33&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:FSS0qP5aV-cJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/senbonzakura.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/platinum_disco_nisemonogatari_op3.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/silhouette_naruto_shippuden_op16.pdf
https://webcache.googleusercontent.com/search?q=cache:mr6CVYfeQl8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/silhouette_naruto_shippuden_op16.pdf+&cd=34&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:mr6CVYfeQl8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/silhouette_naruto_shippuden_op16.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pray_satsuriku_no_tenshi_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pop_team_epic_poputepipikku_op.pdf
https://webcache.googleusercontent.com/search?q=cache:wFMuOw8LGQ8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/refrain_koi_wa_ameagari.pdf+&cd=38&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:wFMuOw8LGQ8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/refrain_koi_wa_ameagari.pdf+
https://webcache.googleusercontent.com/search?q=cache:wJvz_g22T2YJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pop_team_epic_poputepipikku_op.pdf+&cd=31&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:wJvz_g22T2YJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pop_team_epic_poputepipikku_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:GtUXGbDbzjIJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unravel_tokyo_ghoul_op.pdf+&cd=37&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:GtUXGbDbzjIJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unravel_tokyo_ghoul_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:AZz5KpKlALMJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_blue_op_full.pdf+&cd=35&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:AZz5KpKlALMJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_blue_op_full.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_blue_op_full.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unravel_tokyo_ghoul_op.pdf
https://webcache.googleusercontent.com/search?q=cache:Dn8-FiZqfuEJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/platinum_disco_nisemonogatari_op3.pdf+&cd=36&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:Dn8-FiZqfuEJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/platinum_disco_nisemonogatari_op3.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/refrain_koi_wa_ameagari.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/oppai_dragon_no_uta_highschool_dxd_ost.pdf
https://webcache.googleusercontent.com/search?q=cache:nLqdqH7UWskJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/iwanai_kedo_ne_karakai_jouzu.pdf+&cd=39&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:nLqdqH7UWskJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/iwanai_kedo_ne_karakai_jouzu.pdf+
https://webcache.googleusercontent.com/search?q=cache:piECH1qJU-sJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/oppai_dragon_no_uta_highschool_dxd_ost.pdf+&cd=32&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:piECH1qJU-sJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/oppai_dragon_no_uta_highschool_dxd_ost.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/senbonzakura.pdf
https://webcache.googleusercontent.com/search?q=cache:r5UgqJY8D2QJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pray_satsuriku_no_tenshi_ed.pdf+&cd=40&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:r5UgqJY8D2QJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/pray_satsuriku_no_tenshi_ed.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fatima_steins_gate_0_op.pdf
https://webcache.googleusercontent.com/search?q=cache:JVEr1DLVteUJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fiction_wotakoi_op.pdf+&cd=11&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:JVEr1DLVteUJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fiction_wotakoi_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:p91zi-McyRYJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fatima_steins_gate_0_op.pdf+&cd=12&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:p91zi-McyRYJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fatima_steins_gate_0_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kiss_of_death_darling_in_the_franxx_op.pdf
https://webcache.googleusercontent.com/search?q=cache:9f0AzewO8cMJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/error_beatless_op.pdf+&cd=20&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:9f0AzewO8cMJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/error_beatless_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/error_beatless_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/beautiful_world_darling_in_the_franxx_ed3.pdf
https://webcache.googleusercontent.com/search?q=cache:wGQa9MIAe7gJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kiss_of_death_darling_in_the_franxx_op.pdf+&cd=13&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:wGQa9MIAe7gJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kiss_of_death_darling_in_the_franxx_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shiny_days_yuru_camp_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/hitori_darling_in_the_franxx_ed4.pdf
https://webcache.googleusercontent.com/search?q=cache:zq5BR2D5UDQJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/beautiful_world_darling_in_the_franxx_ed3.pdf+&cd=17&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:zq5BR2D5UDQJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/beautiful_world_darling_in_the_franxx_ed3.pdf+
https://webcache.googleusercontent.com/search?q=cache:1SZNrSg9oJ0J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/changing_point_mahou_shoujo_site_op.pdf+&cd=18&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:1SZNrSg9oJ0J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/changing_point_mahou_shoujo_site_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fiction_wotakoi_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/torikago_darling_in_the_franxx_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sincerely_violet_evergarden.pdf
https://webcache.googleusercontent.com/search?q=cache:GMW8IGqyBmsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shiny_days_yuru_camp_op.pdf+&cd=16&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:GMW8IGqyBmsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shiny_days_yuru_camp_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/changing_point_mahou_shoujo_site_op.pdf
https://webcache.googleusercontent.com/search?q=cache:vIrmCMMMVE4J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sincerely_violet_evergarden.pdf+&cd=19&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:vIrmCMMMVE4J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sincerely_violet_evergarden.pdf+
https://webcache.googleusercontent.com/search?q=cache:L0jDKNgpq_cJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/hitori_darling_in_the_franxx_ed4.pdf+&cd=14&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:L0jDKNgpq_cJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/hitori_darling_in_the_franxx_ed4.pdf+
https://webcache.googleusercontent.com/search?q=cache:LQXgFL3VgBIJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/torikago_darling_in_the_franxx_ed.pdf+&cd=15&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:LQXgFL3VgBIJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/torikago_darling_in_the_franxx_ed.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/your_reality_ddlc.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/violet_snow_violet_evergarden_ost.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dango_daikazoku.pdf
https://webcache.googleusercontent.com/search?q=cache:M2qn7WArfwgJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/violet_snow_violet_evergarden_ost.pdf+&cd=25&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:M2qn7WArfwgJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/violet_snow_violet_evergarden_ost.pdf+
https://webcache.googleusercontent.com/search?q=cache:ZG8cGBhN8dkJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dango_daikazoku.pdf+&cd=29&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:ZG8cGBhN8dkJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dango_daikazoku.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/half_tokyo_ghoul_re_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:6hCGftWovk4J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/your_reality_ddlc.pdf+&cd=27&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:6hCGftWovk4J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/your_reality_ddlc.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/ugoku_ugoku_shoujo_shuumatsu.pdf
https://webcache.googleusercontent.com/search?q=cache:KGaeuMLdA5sJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/half_tokyo_ghoul_re_ed.pdf+&cd=22&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:KGaeuMLdA5sJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/half_tokyo_ghoul_re_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:3Xik9-ISTSEJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sugar_song_to_bitter_step_kekkai_sensen_ed.pdf+&cd=26&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:3Xik9-ISTSEJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sugar_song_to_bitter_step_kekkai_sensen_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:VBeat9c72m8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/ugoku_ugoku_shoujo_shuumatsu.pdf+&cd=30&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:VBeat9c72m8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/ugoku_ugoku_shoujo_shuumatsu.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/red_swan_attack_on_titan_s3_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dear_teardrop_citrus_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:WDytgfKuZh8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/red_swan_attack_on_titan_s3_op.pdf+&cd=21&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:WDytgfKuZh8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/red_swan_attack_on_titan_s3_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/michishirube_violet_evergarden_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/aimai_moko_tsurezure_children.pdf
https://webcache.googleusercontent.com/search?q=cache:wLaRtHDYzwgJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dear_teardrop_citrus_ed.pdf+&cd=28&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:wLaRtHDYzwgJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/dear_teardrop_citrus_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:u5x0yOhxNRAJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/michishirube_violet_evergarden_ed.pdf+&cd=23&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:u5x0yOhxNRAJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/michishirube_violet_evergarden_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:hq2rawUDnmAJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/aimai_moko_tsurezure_children.pdf+&cd=24&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:hq2rawUDnmAJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/aimai_moko_tsurezure_children.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/sugar_song_to_bitter_step_kekkai_sensen_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kaen_-_dororo_op.pdf
https://webcache.googleusercontent.com/search?q=cache:8DXuYN5otksJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/lemon_kenshi_yonezu.pdf+&cd=41&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:8DXuYN5otksJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/lemon_kenshi_yonezu.pdf+
https://webcache.googleusercontent.com/search?q=cache:z3V2zNY2H9wJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kaen_-_dororo_op.pdf+&cd=46&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:z3V2zNY2H9wJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kaen_-_dororo_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:vmsl2c6vUdwJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/clear_cardcaptor_sakura.pdf+&cd=42&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:vmsl2c6vUdwJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/clear_cardcaptor_sakura.pdf+
https://webcache.googleusercontent.com/search?q=cache:5sv521n7qigJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/escape_darling_in_the_franxx_ed5.pdf+&cd=44&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:5sv521n7qigJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/escape_darling_in_the_franxx_ed5.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rise_-_tate_no_yuusha_no_nariagari_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/escape_darling_in_the_franxx_ed5.pdf
https://webcache.googleusercontent.com/search?q=cache:aTrJGPvjipsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rise_-_tate_no_yuusha_no_nariagari_op.pdf+&cd=48&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:aTrJGPvjipsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rise_-_tate_no_yuusha_no_nariagari_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/requiem_der_morgenr%C3%B6te_attack_on_titan_s3_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fuyu_biyori_yuru_camp_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/lemon_kenshi_yonezu.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unlasting_-_sword_art_online_alicization_war_of_underworld_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_ni_furete_-_yagate_kimi_ni_naru_op.pdf
https://webcache.googleusercontent.com/search?q=cache:nC_0lMM7XOcJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fuyu_biyori_yuru_camp_ed.pdf+&cd=45&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:nC_0lMM7XOcJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/fuyu_biyori_yuru_camp_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:3urWSalfzWsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_shiranai_monogatari_-_bakemonogatari_ed.pdf+&cd=47&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:3urWSalfzWsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_shiranai_monogatari_-_bakemonogatari_ed.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/clear_cardcaptor_sakura.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_shiranai_monogatari_-_bakemonogatari_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:y2STelpIDYsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/requiem_der_morgenr%25C3%25B6te_attack_on_titan_s3_ed.pdf+&cd=43&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:y2STelpIDYsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/requiem_der_morgenr%25C3%25B6te_attack_on_titan_s3_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:Lrt4MEM-46UJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unlasting_-_sword_art_online_alicization_war_of_underworld_ed.pdf+&cd=49&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:Lrt4MEM-46UJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/unlasting_-_sword_art_online_alicization_war_of_underworld_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:DBzcOY2YDXkJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_ni_furete_-_yagate_kimi_ni_naru_op.pdf+&cd=50&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:DBzcOY2YDXkJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_ni_furete_-_yagate_kimi_ni_naru_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/youthful_beautiful_-_ssss.gridman_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:3eOs6StbzIwJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chikatto_chika_chika__chika_dance__-_kaguya-sama_love_is_war_ed_2.pdf+&cd=78&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:3eOs6StbzIwJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chikatto_chika_chika__chika_dance__-_kaguya-sama_love_is_war_ed_2.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/17_sai_-_irozuku_sekai_no_ashita_kara_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/the_loneliest_girl_-_carole___tuesday_episode_2_ost.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rightfully_-_goblin_slayer_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/daddy__daddy__do__-_kaguya-sama_love_is_war_s2_op.pdf
https://webcache.googleusercontent.com/search?q=cache:mp6GkBa5c1UJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/youthful_beautiful_-_ssss.gridman_ed.pdf+&cd=76&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:mp6GkBa5c1UJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/youthful_beautiful_-_ssss.gridman_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:kmWNfQGQ5vIJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/17_sai_-_irozuku_sekai_no_ashita_kara_op.pdf+&cd=73&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:kmWNfQGQ5vIJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/17_sai_-_irozuku_sekai_no_ashita_kara_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chikatto_chika_chika__chika_dance__-_kaguya-sama_love_is_war_ed_2.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/zero_centimeters_-_karakai_jouzu_no_takagi-san_s2_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otome-domo_yo._-_araburu_kisetsu_no_otome-domo_yo._op.pdf
https://webcache.googleusercontent.com/search?q=cache:KVnMguzS1RsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rightfully_-_goblin_slayer_op.pdf+&cd=71&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:KVnMguzS1RsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/rightfully_-_goblin_slayer_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:-pfKx9lNEpwJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otome-domo_yo._-_araburu_kisetsu_no_otome-domo_yo._op.pdf+&cd=79&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:-pfKx9lNEpwJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otome-domo_yo._-_araburu_kisetsu_no_otome-domo_yo._op.pdf+
https://webcache.googleusercontent.com/search?q=cache:w55KW3FnoeAJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/daddy__daddy__do__-_kaguya-sama_love_is_war_s2_op.pdf+&cd=75&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:w55KW3FnoeAJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/daddy__daddy__do__-_kaguya-sama_love_is_war_s2_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:63ZOC4wDo-8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/the_loneliest_girl_-_carole___tuesday_episode_2_ost.pdf+&cd=72&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:63ZOC4wDo-8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/the_loneliest_girl_-_carole___tuesday_episode_2_ost.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/additional_memory__short_ver.__-_jin.pdf
https://webcache.googleusercontent.com/search?q=cache:7hSkYi5aR88J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/polaris_-_boku_no_hero_academia_season_4_op.pdf+&cd=69&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:7hSkYi5aR88J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/polaris_-_boku_no_hero_academia_season_4_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/gurenge_-_kimetsu_no_yaiba_op.pdf
https://webcache.googleusercontent.com/search?q=cache:oul-zvrTi0YJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kousui_-_eito.pdf+&cd=66&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:oul-zvrTi0YJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kousui_-_eito.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/isabellas_lullaby_-_yakusoku_no_neverland_episode_12_ost.pdf
https://webcache.googleusercontent.com/search?q=cache:050NbiZqB10J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/wild_side_-_beastars_op.pdf+&cd=67&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:050NbiZqB10J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/wild_side_-_beastars_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:74IsHkiRGQYJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_sei_-_seishun_buta_yarou_wa_bunny_girl_senpai_no_yume_wo_minai_op.pdf+&cd=62&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:74IsHkiRGQYJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_sei_-_seishun_buta_yarou_wa_bunny_girl_senpai_no_yume_wo_minai_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/veil_-_fire_force__enen_no_shouboutai_ed_.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kousui_-_eito.pdf
https://webcache.googleusercontent.com/search?q=cache:gg96hDI4Qn8J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_escape_-_weathering_with_you__tenki_no_ko__ost.pdf+&cd=65&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:gg96hDI4Qn8J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_escape_-_weathering_with_you__tenki_no_ko__ost.pdf+
https://webcache.googleusercontent.com/search?q=cache:v_qVJEmjUiUJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/veil_-_fire_force__enen_no_shouboutai_ed_.pdf+&cd=63&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:v_qVJEmjUiUJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/veil_-_fire_force__enen_no_shouboutai_ed_.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/inferno_-_fire_force__enen_no_shouboutai__op.pdf
https://webcache.googleusercontent.com/search?q=cache:e7-264P5NqUJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/gurenge_-_kimetsu_no_yaiba_op.pdf+&cd=70&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:e7-264P5NqUJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/gurenge_-_kimetsu_no_yaiba_op.pdf+
https://webcache.googleusercontent.com/search?q=cache:iNYM2G3nRqwJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otomodachi_film_tada-kun_op.pdf+&cd=61&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:iNYM2G3nRqwJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otomodachi_film_tada-kun_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/grand_escape_-_weathering_with_you__tenki_no_ko__ost.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/polaris_-_boku_no_hero_academia_season_4_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/otomodachi_film_tada-kun_op.pdf
https://webcache.googleusercontent.com/search?q=cache:9IUbQB79xAEJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/isabellas_lullaby_-_yakusoku_no_neverland_episode_12_ost.pdf+&cd=64&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:9IUbQB79xAEJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/isabellas_lullaby_-_yakusoku_no_neverland_episode_12_ost.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_sei_-_seishun_buta_yarou_wa_bunny_girl_senpai_no_yume_wo_minai_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/wild_side_-_beastars_op.pdf
https://webcache.googleusercontent.com/search?q=cache:RUK4mpEW1-UJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/inferno_-_fire_force__enen_no_shouboutai__op.pdf+&cd=68&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:RUK4mpEW1-UJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/inferno_-_fire_force__enen_no_shouboutai__op.pdf+
https://webcache.googleusercontent.com/search?q=cache:Z-h0m1Vgd54J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_namae_-_tate_no_yuusha_no_nariagari_ed.pdf+&cd=55&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:Z-h0m1Vgd54J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_namae_-_tate_no_yuusha_no_nariagari_ed.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/centimeter_-_kanojo_okarishimasu_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimagure_romantic_karakai_jouzu_no_takagi-san_ed.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chiisana_koi_no_uta_karakai_jouzu_no_takagi-san_ed5.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kamado_tanjiro_no_uta_-_kimetsu_no_yaiba_episode_19_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:Y2IRqC3ROfUJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimagure_romantic_karakai_jouzu_no_takagi-san_ed.pdf+&cd=54&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:Y2IRqC3ROfUJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimagure_romantic_karakai_jouzu_no_takagi-san_ed.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kawaki_wo_ameku_-_domestic_na_kanojo_op.pdf
https://webcache.googleusercontent.com/search?q=cache:XV1KRxnvNU0J:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shunkashuutou_-_kimi_no_suizou_wo_tabetai_ed.pdf+&cd=56&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:XV1KRxnvNU0J:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shunkashuutou_-_kimi_no_suizou_wo_tabetai_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:YNPK6yRL_0sJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kamado_tanjiro_no_uta_-_kimetsu_no_yaiba_episode_19_ed.pdf+&cd=60&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:YNPK6yRL_0sJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kamado_tanjiro_no_uta_-_kimetsu_no_yaiba_episode_19_ed.pdf+
https://webcache.googleusercontent.com/search?q=cache:KZ52BeqnpIQJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/niji_no_kanata_ni_-_sao_alicization_ed_3.pdf+&cd=53&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:KZ52BeqnpIQJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/niji_no_kanata_ni_-_sao_alicization_ed_3.pdf+
https://webcache.googleusercontent.com/search?q=cache:C84MCg7t4CsJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/touch_off_-_yakusoku_no_neverland_op.pdf+&cd=57&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:C84MCg7t4CsJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/touch_off_-_yakusoku_no_neverland_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/niji_no_kanata_ni_-_sao_alicization_ed_3.pdf
https://webcache.googleusercontent.com/search?q=cache:dK7xq2GtwCIJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kawaki_wo_ameku_-_domestic_na_kanojo_op.pdf+&cd=58&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:dK7xq2GtwCIJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kawaki_wo_ameku_-_domestic_na_kanojo_op.pdf+
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_no_namae_-_tate_no_yuusha_no_nariagari_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:QFaDQ-7r7qoJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chiisana_koi_no_uta_karakai_jouzu_no_takagi-san_ed5.pdf+&cd=52&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:QFaDQ-7r7qoJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/chiisana_koi_no_uta_karakai_jouzu_no_takagi-san_ed5.pdf+
https://webcache.googleusercontent.com/search?q=cache:DBzcOY2YDXkJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/kimi_ni_furete_-_yagate_kimi_ni_naru_op.pdf+&cd=51&hl=en&ct=clnk&gl=in
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/touch_off_-_yakusoku_no_neverland_op.pdf
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/shunkashuutou_-_kimi_no_suizou_wo_tabetai_ed.pdf
https://webcache.googleusercontent.com/search?q=cache:3mq29njb4_kJ:https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/centimeter_-_kanojo_okarishimasu_op.pdf+&cd=59&hl=en&ct=clnk&gl=in
https://webcache.googleusercontent.com/search?q=cache:3mq29njb4_kJ:
https://stevehansenyt.weebly.com/uploads/4/1/5/4/41543939/centimeter_-_kanojo_okarishimasu_op.pdf+
'''
links_list = links.split('\n')
for url in links_list:
    if 'cache' in url:
        x = re.search(r'search.+(http.+pdf)', url)
        if x:
            print(x.group(1))
    else:
        print(url)